### ISSUE TITLE
Detecting objects 

### ISSUE THREAD

**Issue by hunaidkhan2000** [infparadox/Object-Tracking-and-Detection#1]
Hi Awesome work in this code i wanted to know that how can i count all the objects in a this video and save it to a CSV file or database file. 

2) also in your code.py what is the value of enter initial x for line1 etc.

**Comment by infparadox** [comment]
I am saving all the contents in a file and assigning a unique id to each vehicle. For initial x and initial y  you can try this value : 
1) initial_ x1= 0.3 , initial _y1 = 0.3 , final_x1 = 0.8 , final_y1=0.3
2)  initial_ x1= 0.3 , initial _y1 = 0.8 , final_x1 = 0.8 , final_y1=0.8
These values are basically in a scale of (0,1) and these are the coordinates for line1,line2.
